import { SampleTemplate } from './email-template-builder.models';

export const EMAIL_SAMPLE_TEMPLATES: SampleTemplate[] = [
  {
    id: 'otp-verification',
    name: 'OTP Verification',
    description: 'Secure one-time password delivery with a prominent code display and verify button.',
    icon: 'verified_user',
    category: 'Authentication',
    accentColor: '#0ea5e9',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Security Notice', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'text', label: 'Intro', icon: 'subject', title: 'Verify your email address', text: 'Use the one-time passcode below to verify your email. Expires in 10 minutes — do not share it.', backgroundColor: '#ffffff', textColor: '#475569', textAlign: 'center', padding: 36, radius: 0 },
      { id: 3, type: 'coupon', label: 'OTP Code', icon: 'sell', title: 'Your one-time passcode', text: '482 916', secondaryText: 'Expires in 10 minutes · Do not share', backgroundColor: '#f0f9ff', textColor: '#0369a1', textAlign: 'center', padding: 32, radius: 14 },
      { id: 4, type: 'button', label: 'Verify Button', icon: 'smart_button', text: 'Verify My Email', url: 'https://nowmail.app/verify', backgroundColor: '#ffffff', buttonColor: '#0ea5e9', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'text', label: 'Help Note', icon: 'subject', title: '', text: "Didn't request this? Ignore this email. No changes will be made.", backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
      { id: 6, type: 'footer', label: 'Footer', icon: 'notes', text: 'You are receiving this because you signed up at {{company_name}}. Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'login-alert',
    name: 'Login Alert',
    description: 'Notify users of a new sign-in with device details and a security action button.',
    icon: 'lock_open',
    category: 'Security',
    accentColor: '#f59e0b',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Security Alert', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'badge', label: 'Alert Badge', icon: 'verified', text: '🔐 New Login Detected', backgroundColor: '#fef9c3', textColor: '#854d0e', textAlign: 'center', padding: 20, radius: 999 },
      { id: 3, type: 'text', label: 'Details', icon: 'subject', title: 'A new sign-in to your account', text: 'We noticed a new login to your {{company_name}} account. If this was you, no action is needed.', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 32, radius: 0 },
      { id: 4, type: 'list', label: 'Login Info', icon: 'format_list_bulleted', title: 'Login details', text: 'Time: Today at {{login_time}}\nDevice: Chrome on Windows\nLocation: India', backgroundColor: '#f8fafc', textColor: '#475569', textAlign: 'left', padding: 28, radius: 0 },
      { id: 5, type: 'button', label: 'Secure Account', icon: 'smart_button', text: 'Secure My Account', url: 'https://nowmail.app/security', backgroundColor: '#ffffff', buttonColor: '#dc2626', buttonTextColor: '#ffffff', textAlign: 'center', padding: 28, radius: 8 },
      { id: 6, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} Security Team · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#9ca3af', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'welcome-email',
    name: 'Welcome Email',
    description: 'Warm onboarding email that introduces your product and guides users to get started.',
    icon: 'waving_hand',
    category: 'Onboarding',
    accentColor: '#10b981',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'View online', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'hero', label: 'Welcome Hero', icon: 'image', title: 'Welcome to {{company_name}}, {{first_name}}! 🎉', text: "We're thrilled to have you on board. Your account is ready — let's get started.", imageUrl: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=80', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 32, radius: 0 },
      { id: 3, type: 'list', label: 'Key Features', icon: 'format_list_bulleted', title: 'What you can do', text: 'Build beautiful email campaigns\nAutomate onboarding flows\nTrack opens and clicks\nPersonalize with variables', backgroundColor: '#f0fdf4', textColor: '#166534', textAlign: 'left', padding: 32, radius: 0 },
      { id: 4, type: 'button', label: 'CTA', icon: 'smart_button', text: 'Open Your Dashboard →', url: 'https://nowmail.app/dashboard', backgroundColor: '#ffffff', buttonColor: '#10b981', buttonTextColor: '#ffffff', textAlign: 'center', padding: 28, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '© 2026 {{company_name}} · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 22, radius: 0 },
    ],
  },
  {
    id: 'newsletter',
    name: 'Newsletter',
    description: 'Engaging newsletter layout with hero image, featured article, and social links.',
    icon: 'newspaper',
    category: 'Marketing',
    accentColor: '#8b5cf6',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}} Weekly', text: 'View in browser', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'hero', label: 'Hero', icon: 'image', title: "This Week's Top Story", text: 'Discover the latest updates and curated insights from {{company_name}}.', imageUrl: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=1200&q=80', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 32, radius: 0 },
      { id: 3, type: 'text', label: 'Article', icon: 'subject', title: 'Building Better Workflows', text: 'Teams are using automation and smarter templates to cut email production time by 60%.', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'left', padding: 32, radius: 0 },
      { id: 4, type: 'button', label: 'Read More', icon: 'smart_button', text: 'Read Full Article →', url: 'https://nowmail.app/blog', backgroundColor: '#ffffff', buttonColor: '#8b5cf6', buttonTextColor: '#ffffff', textAlign: 'center', padding: 16, radius: 8 },
      { id: 5, type: 'quote', label: 'Quote', icon: 'format_quote', text: 'A great email template is not just beautiful — it\'s a conversation starter.', title: 'Head of Growth, {{company_name}}', backgroundColor: '#f5f3ff', textColor: '#5b21b6', textAlign: 'center', padding: 36, radius: 0 },
      { id: 6, type: 'social', label: 'Social', icon: 'share', text: 'Follow us', backgroundColor: '#f8fafc', textColor: '#64748b', textAlign: 'center', padding: 28, radius: 0, socialLinks: [{ type: 'twitter', url: 'https://twitter.com' }, { type: 'linkedin', url: 'https://linkedin.com' }, { type: 'website', url: 'https://nowmail.app' }] },
      { id: 7, type: 'footer', label: 'Footer', icon: 'notes', text: '© 2026 {{company_name}}. Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'password-reset',
    name: 'Password Reset',
    description: 'Clean password reset email with a secure link and expiry warning.',
    icon: 'lock_reset',
    category: 'Authentication',
    accentColor: '#ef4444',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Security', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'text', label: 'Intro', icon: 'subject', title: 'Reset your password', text: 'We received a request to reset your password. Click the button below to choose a new one.', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 36, radius: 0 },
      { id: 3, type: 'button', label: 'Reset Button', icon: 'smart_button', text: 'Reset My Password', url: '{{reset_url}}', backgroundColor: '#ffffff', buttonColor: '#ef4444', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 4, type: 'badge', label: 'Expiry Notice', icon: 'verified', text: '⏱ This link expires in 24 hours', backgroundColor: '#fef2f2', textColor: '#b91c1c', textAlign: 'center', padding: 16, radius: 8 },
      { id: 5, type: 'text', label: 'Safety Note', icon: 'subject', title: '', text: "If you didn't request a password reset, ignore this email. Your password won't change.", backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
      { id: 6, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'flash-sale',
    name: 'Flash Sale',
    description: 'High-energy promotional email with bold discount coupon and countdown urgency.',
    icon: 'local_fire_department',
    category: 'Promotion',
    accentColor: '#f97316',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Shop Now', url: 'https://nowmail.app/shop', backgroundColor: '#fff7ed', textColor: '#9a3412', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'hero', label: 'Sale Hero', icon: 'image', title: '🔥 Flash Sale — 48 Hours Only!', text: 'Up to 70% off on all products. Hurry, stocks are limited!', imageUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=1200&q=80', backgroundColor: '#fff7ed', textColor: '#9a3412', textAlign: 'center', padding: 32, radius: 0 },
      { id: 3, type: 'coupon', label: 'Promo Code', icon: 'sell', title: 'Use code at checkout', text: 'FLASH70', secondaryText: '70% off · Ends {{sale_end_date}}', backgroundColor: '#ffedd5', textColor: '#c2410c', textAlign: 'center', padding: 32, radius: 12 },
      { id: 4, type: 'button', label: 'Shop Now', icon: 'smart_button', text: 'Shop the Sale →', url: 'https://nowmail.app/sale', backgroundColor: '#fff7ed', buttonColor: '#f97316', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '© 2026 {{company_name}} · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'order-confirmation',
    name: 'Order Confirmation',
    description: 'Professional e-commerce order confirmation with item summary and tracking link.',
    icon: 'shopping_bag',
    category: 'E-Commerce',
    accentColor: '#06b6d4',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Order Confirmed', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'badge', label: 'Status Badge', icon: 'verified', text: '✅ Order Confirmed!', backgroundColor: '#ecfdf5', textColor: '#065f46', textAlign: 'center', padding: 20, radius: 999 },
      { id: 3, type: 'text', label: 'Order Info', icon: 'subject', title: 'Thank you, {{first_name}}!', text: 'Your order #{{order_id}} has been placed and is being processed. You will receive a shipping update soon.', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 28, radius: 0 },
      { id: 4, type: 'list', label: 'Order Summary', icon: 'format_list_bulleted', title: 'Order Summary', text: 'Order ID: {{order_id}}\nItems: {{item_count}}\nTotal: {{order_total}}\nDelivery by: {{delivery_date}}', backgroundColor: '#f0fdfa', textColor: '#134e4a', textAlign: 'left', padding: 28, radius: 0 },
      { id: 5, type: 'button', label: 'Track Order', icon: 'smart_button', text: 'Track Your Order', url: '{{tracking_url}}', backgroundColor: '#ffffff', buttonColor: '#06b6d4', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 6, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} · Questions? Contact support@{{company_domain}} · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'account-suspended',
    name: 'Account Suspended',
    description: 'Formal account suspension notice with reason details and appeal options.',
    icon: 'block',
    category: 'Security',
    accentColor: '#dc2626',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Account Notice', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'badge', label: 'Status', icon: 'verified', text: '🚫 Account Suspended', backgroundColor: '#fef2f2', textColor: '#b91c1c', textAlign: 'center', padding: 20, radius: 999 },
      { id: 3, type: 'text', label: 'Details', icon: 'subject', title: 'Your account has been suspended', text: 'We have temporarily suspended your account due to a violation of our terms of service. Please review the details below.', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 32, radius: 0 },
      { id: 4, type: 'list', label: 'Reason', icon: 'format_list_bulleted', title: 'Suspension details', text: 'Reason: {{suspension_reason}}\nDate: {{suspension_date}}\nDuration: {{suspension_duration}}', backgroundColor: '#fef2f2', textColor: '#7f1d1d', textAlign: 'left', padding: 28, radius: 0 },
      { id: 5, type: 'button', label: 'Appeal', icon: 'smart_button', text: 'Submit an Appeal', url: 'https://nowmail.app/appeal', backgroundColor: '#ffffff', buttonColor: '#dc2626', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 6, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} Trust & Safety · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'invoice',
    name: 'Invoice / Receipt',
    description: 'Clean billing invoice email with itemized breakdown and payment confirmation.',
    icon: 'receipt_long',
    category: 'Finance',
    accentColor: '#3b82f6',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Billing', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'text', label: 'Invoice Title', icon: 'subject', title: 'Invoice #{{invoice_id}}', text: 'Your payment has been received. Here is your invoice for the billing period {{billing_period}}.', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'left', padding: 32, radius: 0 },
      { id: 3, type: 'list', label: 'Line Items', icon: 'format_list_bulleted', title: 'Billing Summary', text: 'Plan: {{plan_name}}\nPeriod: {{billing_period}}\nSubtotal: {{subtotal}}\nTax: {{tax}}\nTotal Paid: {{total}}', backgroundColor: '#eff6ff', textColor: '#1e3a8a', textAlign: 'left', padding: 28, radius: 0 },
      { id: 4, type: 'button', label: 'Download', icon: 'smart_button', text: 'Download PDF Invoice', url: '{{invoice_url}}', backgroundColor: '#ffffff', buttonColor: '#3b82f6', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} Billing · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'product-launch',
    name: 'Product Launch',
    description: 'Exciting product launch announcement with feature highlights and early access CTA.',
    icon: 'rocket_launch',
    category: 'Marketing',
    accentColor: '#7c3aed',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'New Product', url: 'https://nowmail.app', backgroundColor: '#faf5ff', textColor: '#4c1d95', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'hero', label: 'Launch Hero', icon: 'image', title: '🚀 Introducing {{product_name}}', text: 'The future of {{product_category}} is here. Be among the first to experience it.', imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80', backgroundColor: '#faf5ff', textColor: '#4c1d95', textAlign: 'center', padding: 40, radius: 0 },
      { id: 3, type: 'list', label: 'Features', icon: 'format_list_bulleted', title: 'Key Features', text: '{{feature_1}}\n{{feature_2}}\n{{feature_3}}\n{{feature_4}}', backgroundColor: '#f5f3ff', textColor: '#4c1d95', textAlign: 'left', padding: 32, radius: 0 },
      { id: 4, type: 'button', label: 'Get Early Access', icon: 'smart_button', text: 'Get Early Access →', url: '{{product_url}}', backgroundColor: '#faf5ff', buttonColor: '#7c3aed', buttonTextColor: '#ffffff', textAlign: 'center', padding: 28, radius: 8 },
      { id: 5, type: 'social', label: 'Social', icon: 'share', text: 'Share the launch', backgroundColor: '#f8fafc', textColor: '#64748b', textAlign: 'center', padding: 24, radius: 0, socialLinks: [{ type: 'twitter', url: 'https://twitter.com' }, { type: 'linkedin', url: 'https://linkedin.com' }, { type: 'facebook', url: 'https://facebook.com' }] },
      { id: 6, type: 'footer', label: 'Footer', icon: 'notes', text: '© 2026 {{company_name}} · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'shipping-update',
    name: 'Shipping Update',
    description: 'Real-time shipment tracking update with carrier info and estimated delivery.',
    icon: 'local_shipping',
    category: 'E-Commerce',
    accentColor: '#0891b2',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Track Order', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'badge', label: 'Status', icon: 'verified', text: '📦 Your Order is on its Way!', backgroundColor: '#e0f2fe', textColor: '#0c4a6e', textAlign: 'center', padding: 20, radius: 999 },
      { id: 3, type: 'text', label: 'Info', icon: 'subject', title: 'Shipment dispatched', text: 'Great news! Your order #{{order_id}} has been shipped and is on its way to you.', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 28, radius: 0 },
      { id: 4, type: 'list', label: 'Tracking Info', icon: 'format_list_bulleted', title: 'Shipment Details', text: 'Carrier: {{carrier}}\nTracking #: {{tracking_number}}\nEstimated Delivery: {{delivery_date}}', backgroundColor: '#f0f9ff', textColor: '#0c4a6e', textAlign: 'left', padding: 28, radius: 0 },
      { id: 5, type: 'button', label: 'Track', icon: 'smart_button', text: 'Track My Package', url: '{{tracking_url}}', backgroundColor: '#ffffff', buttonColor: '#0891b2', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 6, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'abandoned-cart',
    name: 'Abandoned Cart',
    description: 'Recover lost sales with a friendly reminder and special discount incentive.',
    icon: 'shopping_cart',
    category: 'E-Commerce',
    accentColor: '#f43f5e',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Your Cart', url: 'https://nowmail.app/cart', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'text', label: 'Reminder', icon: 'subject', title: 'You left something behind, {{first_name}}!', text: 'Your cart is missing you. The items you selected are still available — but not for long!', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 32, radius: 0 },
      { id: 3, type: 'coupon', label: 'Discount', icon: 'sell', title: 'Complete your order & save', text: 'SAVE15', secondaryText: '15% off your cart · Limited time', backgroundColor: '#fff1f2', textColor: '#be123c', textAlign: 'center', padding: 32, radius: 12 },
      { id: 4, type: 'button', label: 'Return to Cart', icon: 'smart_button', text: 'Return to My Cart →', url: '{{cart_url}}', backgroundColor: '#ffffff', buttonColor: '#f43f5e', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'job-offer',
    name: 'Job Offer Letter',
    description: 'Professional job offer email with role details, compensation, and acceptance CTA.',
    icon: 'work',
    category: 'HR',
    accentColor: '#0d9488',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Human Resources', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'text', label: 'Offer', icon: 'subject', title: 'Congratulations, {{first_name}}! 🎉', text: 'We are delighted to offer you the position of {{job_title}} at {{company_name}}. We believe your skills are an excellent fit for our team.', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 32, radius: 0 },
      { id: 3, type: 'list', label: 'Offer Details', icon: 'format_list_bulleted', title: 'Offer Details', text: 'Role: {{job_title}}\nDepartment: {{department}}\nStart Date: {{start_date}}\nSalary: {{salary}}\nLocation: {{location}}', backgroundColor: '#f0fdfa', textColor: '#134e4a', textAlign: 'left', padding: 32, radius: 0 },
      { id: 4, type: 'button', label: 'Accept Offer', icon: 'smart_button', text: 'Accept This Offer', url: '{{offer_url}}', backgroundColor: '#ffffff', buttonColor: '#0d9488', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'text', label: 'Note', icon: 'subject', title: '', text: 'Please accept or decline by {{deadline_date}}. For any questions, contact HR at {{hr_email}}.', backgroundColor: '#f8fafc', textColor: '#64748b', textAlign: 'center', padding: 24, radius: 0 },
      { id: 6, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} HR Team · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'appointment-reminder',
    name: 'Appointment Reminder',
    description: 'Medical appointment reminder with date, doctor details, and preparation instructions.',
    icon: 'calendar_month',
    category: 'Healthcare',
    accentColor: '#059669',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{clinic_name}}', text: 'Health Portal', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'badge', label: 'Reminder', icon: 'verified', text: '🗓 Upcoming Appointment', backgroundColor: '#ecfdf5', textColor: '#065f46', textAlign: 'center', padding: 20, radius: 999 },
      { id: 3, type: 'text', label: 'Details', icon: 'subject', title: 'Your appointment is confirmed', text: 'This is a friendly reminder of your upcoming appointment at {{clinic_name}}. Please arrive 10 minutes early.', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 28, radius: 0 },
      { id: 4, type: 'list', label: 'Appointment Info', icon: 'format_list_bulleted', title: 'Appointment Details', text: 'Doctor: Dr. {{doctor_name}}\nDate: {{appointment_date}}\nTime: {{appointment_time}}\nLocation: {{clinic_address}}', backgroundColor: '#f0fdf4', textColor: '#14532d', textAlign: 'left', padding: 28, radius: 0 },
      { id: 5, type: 'button', label: 'Manage', icon: 'smart_button', text: 'View / Reschedule', url: '{{appointment_url}}', backgroundColor: '#ffffff', buttonColor: '#059669', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 6, type: 'footer', label: 'Footer', icon: 'notes', text: '{{clinic_name}} · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'course-enrollment',
    name: 'Course Enrollment',
    description: 'E-learning enrollment confirmation with course details and start guide.',
    icon: 'school',
    category: 'Education',
    accentColor: '#6366f1',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'My Learning', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'hero', label: 'Hero', icon: 'image', title: "You're enrolled in {{course_name}}!", text: 'Your learning journey begins now. Get ready to gain new skills and advance your career.', imageUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80', backgroundColor: '#eef2ff', textColor: '#3730a3', textAlign: 'center', padding: 36, radius: 0 },
      { id: 3, type: 'list', label: 'Course Details', icon: 'format_list_bulleted', title: 'Course Info', text: 'Course: {{course_name}}\nInstructor: {{instructor_name}}\nDuration: {{course_duration}}\nStarts: {{start_date}}', backgroundColor: '#eef2ff', textColor: '#3730a3', textAlign: 'left', padding: 28, radius: 0 },
      { id: 4, type: 'button', label: 'Start Learning', icon: 'smart_button', text: 'Start Learning →', url: '{{course_url}}', backgroundColor: '#ffffff', buttonColor: '#6366f1', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} Education · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'subscription-renewal',
    name: 'Subscription Renewal',
    description: 'Upcoming subscription renewal notice with plan details and manage link.',
    icon: 'autorenew',
    category: 'Finance',
    accentColor: '#2563eb',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Billing', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'text', label: 'Notice', icon: 'subject', title: 'Your subscription renews soon', text: 'Your {{plan_name}} plan will automatically renew on {{renewal_date}}. No action needed unless you want to make changes.', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 32, radius: 0 },
      { id: 3, type: 'list', label: 'Plan Details', icon: 'format_list_bulleted', title: 'Renewal Summary', text: 'Plan: {{plan_name}}\nRenewal Date: {{renewal_date}}\nAmount: {{renewal_amount}}\nPayment Method: {{payment_method}}', backgroundColor: '#eff6ff', textColor: '#1e3a8a', textAlign: 'left', padding: 28, radius: 0 },
      { id: 4, type: 'button', label: 'Manage', icon: 'smart_button', text: 'Manage Subscription', url: '{{billing_url}}', backgroundColor: '#ffffff', buttonColor: '#2563eb', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} Billing · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'event-invitation',
    name: 'Event Invitation',
    description: 'Elegant event invitation with venue details, schedule, and RSVP button.',
    icon: 'event',
    category: 'Events',
    accentColor: '#ec4899',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Events', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'hero', label: 'Event Hero', icon: 'image', title: "You're Invited! 🎟", text: 'Join us for {{event_name}} — an unforgettable experience on {{event_date}} at {{event_venue}}.', imageUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80', backgroundColor: '#fdf2f8', textColor: '#831843', textAlign: 'center', padding: 36, radius: 0 },
      { id: 3, type: 'list', label: 'Event Details', icon: 'format_list_bulleted', title: 'Event Details', text: 'Date: {{event_date}}\nTime: {{event_time}}\nVenue: {{event_venue}}\nDress Code: {{dress_code}}', backgroundColor: '#fdf2f8', textColor: '#831843', textAlign: 'left', padding: 28, radius: 0 },
      { id: 4, type: 'button', label: 'RSVP', icon: 'smart_button', text: 'RSVP Now →', url: '{{rsvp_url}}', backgroundColor: '#ffffff', buttonColor: '#ec4899', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} Events · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'feedback-request',
    name: 'Feedback Request',
    description: 'Post-purchase feedback survey with star rating prompt and incentive.',
    icon: 'star_rate',
    category: 'Marketing',
    accentColor: '#f59e0b',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Share Feedback', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'text', label: 'Ask', icon: 'subject', title: 'How was your experience, {{first_name}}?', text: 'We hope you enjoyed your recent order. Your feedback helps us improve and serve you better. It only takes 1 minute!', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 32, radius: 0 },
      { id: 3, type: 'coupon', label: 'Incentive', icon: 'sell', title: 'Leave a review & get', text: '10% OFF', secondaryText: 'Your next purchase', backgroundColor: '#fefce8', textColor: '#92400e', textAlign: 'center', padding: 28, radius: 12 },
      { id: 4, type: 'button', label: 'Rate Us', icon: 'smart_button', text: '⭐ Leave a Review', url: '{{review_url}}', backgroundColor: '#ffffff', buttonColor: '#f59e0b', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'referral-program',
    name: 'Referral Program',
    description: 'Referral invite email with unique code, reward breakdown, and sharing CTA.',
    icon: 'group_add',
    category: 'Marketing',
    accentColor: '#14b8a6',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Refer & Earn', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'text', label: 'Intro', icon: 'subject', title: 'Earn rewards by referring friends!', text: 'Share your unique referral link and earn {{reward_amount}} for every friend who signs up and makes their first purchase.', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 32, radius: 0 },
      { id: 3, type: 'coupon', label: 'Referral Code', icon: 'sell', title: 'Your referral code', text: '{{referral_code}}', secondaryText: 'Share this with your friends', backgroundColor: '#f0fdfa', textColor: '#0f766e', textAlign: 'center', padding: 28, radius: 12 },
      { id: 4, type: 'button', label: 'Share', icon: 'smart_button', text: 'Share Your Link →', url: '{{referral_url}}', backgroundColor: '#ffffff', buttonColor: '#14b8a6', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'annual-report',
    name: 'Annual Report',
    description: 'Corporate annual report summary with key metrics, milestones, and shareholder CTA.',
    icon: 'bar_chart',
    category: 'Corporate',
    accentColor: '#1e40af',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Annual Report {{year}}', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'hero', label: 'Report Hero', icon: 'image', title: '{{company_name}} Annual Report {{year}}', text: 'A year of growth, innovation, and impact. Here is a summary of our key achievements.', imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80', backgroundColor: '#eff6ff', textColor: '#1e3a8a', textAlign: 'center', padding: 36, radius: 0 },
      { id: 3, type: 'list', label: 'Highlights', icon: 'format_list_bulleted', title: 'Key Highlights', text: 'Revenue: {{annual_revenue}}\nNew Customers: {{new_customers}}\nEmployee Count: {{employee_count}}\nMarkets Served: {{markets}}', backgroundColor: '#eff6ff', textColor: '#1e3a8a', textAlign: 'left', padding: 28, radius: 0 },
      { id: 4, type: 'button', label: 'Full Report', icon: 'smart_button', text: 'Read Full Report', url: '{{report_url}}', backgroundColor: '#ffffff', buttonColor: '#1e40af', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} Investor Relations · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'trial-expiry',
    name: 'Trial Expiring Soon',
    description: 'Remind free-trial users to upgrade before their trial ends with a clear CTA.',
    icon: 'hourglass_bottom',
    category: 'SaaS',
    accentColor: '#7c3aed',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Account', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'badge', label: 'Warning', icon: 'verified', text: '⏳ Your trial ends in {{days_left}} days', backgroundColor: '#faf5ff', textColor: '#6d28d9', textAlign: 'center', padding: 18, radius: 999 },
      { id: 3, type: 'text', label: 'Body', icon: 'subject', title: "Don't lose access to {{company_name}}", text: 'Upgrade now to keep your data, workflows, and access uninterrupted. Choose the plan that fits you best.', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 32, radius: 0 },
      { id: 4, type: 'button', label: 'Upgrade', icon: 'smart_button', text: 'Upgrade My Plan →', url: '{{upgrade_url}}', backgroundColor: '#ffffff', buttonColor: '#7c3aed', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'property-listing',
    name: 'Property Listing Alert',
    description: 'Real estate new listing alert with property specs, images, and contact CTA.',
    icon: 'home',
    category: 'Real Estate',
    accentColor: '#b45309',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{agency_name}}', text: 'New Listings', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'hero', label: 'Property', icon: 'image', title: '🏠 New Property Available!', text: '{{property_address}} · {{property_type}} · {{bedrooms}} bed / {{bathrooms}} bath', imageUrl: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80', backgroundColor: '#fffbeb', textColor: '#78350f', textAlign: 'center', padding: 32, radius: 0 },
      { id: 3, type: 'list', label: 'Details', icon: 'format_list_bulleted', title: 'Property Details', text: 'Price: {{price}}\nArea: {{area}} sq ft\nType: {{property_type}}\nAvailable: {{available_date}}', backgroundColor: '#fffbeb', textColor: '#78350f', textAlign: 'left', padding: 28, radius: 0 },
      { id: 4, type: 'button', label: 'View', icon: 'smart_button', text: 'Schedule a Viewing', url: '{{listing_url}}', backgroundColor: '#ffffff', buttonColor: '#b45309', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{agency_name}} · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'flight-booking',
    name: 'Flight Booking Confirmation',
    description: 'Travel booking confirmation with itinerary, seat info, and check-in CTA.',
    icon: 'flight_takeoff',
    category: 'Travel',
    accentColor: '#0369a1',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'My Trips', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'badge', label: 'Status', icon: 'verified', text: '✈️ Booking Confirmed!', backgroundColor: '#e0f2fe', textColor: '#0c4a6e', textAlign: 'center', padding: 20, radius: 999 },
      { id: 3, type: 'list', label: 'Itinerary', icon: 'format_list_bulleted', title: 'Flight Details', text: 'Flight: {{flight_number}}\nFrom: {{origin}} → To: {{destination}}\nDate: {{departure_date}}\nDeparture: {{departure_time}}\nSeat: {{seat_number}}\nBooking Ref: {{booking_ref}}', backgroundColor: '#f0f9ff', textColor: '#0c4a6e', textAlign: 'left', padding: 28, radius: 0 },
      { id: 4, type: 'button', label: 'Check In', icon: 'smart_button', text: 'Online Check-In →', url: '{{checkin_url}}', backgroundColor: '#ffffff', buttonColor: '#0369a1', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} Travel · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'donation-receipt',
    name: 'Donation Receipt',
    description: 'Nonprofit tax-deductible donation receipt with impact statement and share CTA.',
    icon: 'volunteer_activism',
    category: 'Nonprofit',
    accentColor: '#16a34a',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{org_name}}', text: 'Donation Receipt', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'text', label: 'Thanks', icon: 'subject', title: 'Thank you for your generosity, {{first_name}}! 💚', text: 'Your donation of {{amount}} on {{donation_date}} makes a real difference. This email serves as your official tax receipt.', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 32, radius: 0 },
      { id: 3, type: 'list', label: 'Receipt', icon: 'format_list_bulleted', title: 'Donation Details', text: 'Amount: {{amount}}\nDate: {{donation_date}}\nTransaction ID: {{transaction_id}}\nOrg EIN: {{ein_number}}', backgroundColor: '#f0fdf4', textColor: '#14532d', textAlign: 'left', padding: 28, radius: 0 },
      { id: 4, type: 'button', label: 'Share', icon: 'smart_button', text: 'Spread the Word', url: '{{share_url}}', backgroundColor: '#ffffff', buttonColor: '#16a34a', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{org_name}} is a registered nonprofit · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'api-downtime',
    name: 'API / Service Downtime',
    description: 'IT incident notification for service disruption with status page and ETA.',
    icon: 'cloud_off',
    category: 'IT / DevOps',
    accentColor: '#dc2626',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}} Status', text: 'Incident Report', url: 'https://nowmail.app/status', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'badge', label: 'Alert', icon: 'verified', text: '🔴 Service Disruption Detected', backgroundColor: '#fef2f2', textColor: '#b91c1c', textAlign: 'center', padding: 18, radius: 999 },
      { id: 3, type: 'text', label: 'Details', icon: 'subject', title: 'We are investigating an issue', text: 'Our team is actively working to resolve the issue affecting {{affected_service}}. We apologize for the inconvenience.', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 28, radius: 0 },
      { id: 4, type: 'list', label: 'Incident Info', icon: 'format_list_bulleted', title: 'Incident Details', text: 'Service: {{affected_service}}\nStarted: {{incident_start}}\nEstimated Fix: {{eta}}\nIncident ID: {{incident_id}}', backgroundColor: '#fef2f2', textColor: '#7f1d1d', textAlign: 'left', padding: 28, radius: 0 },
      { id: 5, type: 'button', label: 'Status', icon: 'smart_button', text: 'View Status Page', url: '{{status_url}}', backgroundColor: '#ffffff', buttonColor: '#dc2626', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 6, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} Engineering · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'pr-announcement',
    name: 'Press Release',
    description: 'Corporate press release announcement with key message and media contact info.',
    icon: 'campaign',
    category: 'Corporate',
    accentColor: '#0f172a',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Press Release', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'text', label: 'Release', icon: 'subject', title: '{{headline}}', text: '{{company_name}} today announced {{announcement_summary}}. This marks a significant milestone in the company\'s mission to {{company_mission}}.', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'left', padding: 32, radius: 0 },
      { id: 3, type: 'quote', label: 'Quote', icon: 'format_quote', text: '"{{executive_quote}}"', title: '{{executive_name}}, {{executive_title}} at {{company_name}}', backgroundColor: '#f1f5f9', textColor: '#0f172a', textAlign: 'center', padding: 32, radius: 0 },
      { id: 4, type: 'button', label: 'Full Release', icon: 'smart_button', text: 'Read Full Press Release', url: '{{press_url}}', backgroundColor: '#ffffff', buttonColor: '#0f172a', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: 'Media Contact: {{pr_contact}} · {{company_name}} · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'gdpr-data-request',
    name: 'GDPR Data Request',
    description: 'Compliance email confirming user data export request with download link.',
    icon: 'privacy_tip',
    category: 'Compliance',
    accentColor: '#4338ca',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Privacy Center', url: 'https://nowmail.app/privacy', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'text', label: 'Confirm', icon: 'subject', title: 'Your data is ready to download', text: 'We have processed your data export request. Your personal data archive is now available for download. The link expires in 48 hours.', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 32, radius: 0 },
      { id: 3, type: 'badge', label: 'Expiry', icon: 'verified', text: '⏱ Link expires in 48 hours', backgroundColor: '#eef2ff', textColor: '#3730a3', textAlign: 'center', padding: 16, radius: 8 },
      { id: 4, type: 'button', label: 'Download', icon: 'smart_button', text: 'Download My Data', url: '{{data_download_url}}', backgroundColor: '#ffffff', buttonColor: '#4338ca', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} Privacy Team · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'employee-onboarding',
    name: 'Employee Onboarding',
    description: 'First-day onboarding email for new hires with schedule, resources, and IT setup links.',
    icon: 'badge',
    category: 'HR',
    accentColor: '#0891b2',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Welcome Aboard', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'text', label: 'Welcome', icon: 'subject', title: "Welcome to the team, {{first_name}}! 🎉", text: "We're so excited to have you join {{company_name}}. Here's everything you need to know for your first day.", backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 32, radius: 0 },
      { id: 3, type: 'list', label: 'First Day Info', icon: 'format_list_bulleted', title: 'Your First Day', text: 'Date: {{start_date}}\nReporting Time: {{report_time}}\nOffice: {{office_address}}\nManager: {{manager_name}}\nIT Setup: {{it_setup_url}}', backgroundColor: '#e0f2fe', textColor: '#0c4a6e', textAlign: 'left', padding: 28, radius: 0 },
      { id: 4, type: 'button', label: 'Portal', icon: 'smart_button', text: 'Access Employee Portal', url: '{{portal_url}}', backgroundColor: '#ffffff', buttonColor: '#0891b2', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} People Team · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'two-factor-enabled',
    name: '2FA Enabled',
    description: 'Security confirmation that two-factor authentication has been successfully enabled.',
    icon: 'security',
    category: 'Authentication',
    accentColor: '#059669',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Security', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'badge', label: 'Status', icon: 'verified', text: '🛡️ Two-Factor Auth Enabled', backgroundColor: '#ecfdf5', textColor: '#065f46', textAlign: 'center', padding: 20, radius: 999 },
      { id: 3, type: 'text', label: 'Confirm', icon: 'subject', title: 'Your account is now more secure', text: 'Two-factor authentication has been enabled on your {{company_name}} account. You will now be required to enter a code each time you log in.', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 32, radius: 0 },
      { id: 4, type: 'text', label: 'Warning', icon: 'subject', title: '', text: "If you didn't enable 2FA, please contact our support team immediately and secure your account.", backgroundColor: '#fef2f2', textColor: '#b91c1c', textAlign: 'center', padding: 20, radius: 8 },
      { id: 5, type: 'button', label: 'Manage', icon: 'smart_button', text: 'Manage Security Settings', url: '{{security_url}}', backgroundColor: '#ffffff', buttonColor: '#059669', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 6, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} Security · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'seasonal-promo',
    name: 'Seasonal Promotion',
    description: 'Holiday/seasonal promotional blast with festive design, discount code, and shop CTA.',
    icon: 'celebration',
    category: 'Promotion',
    accentColor: '#dc2626',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Special Offers', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'hero', label: 'Promo Hero', icon: 'image', title: '{{season}} Sale is here! 🎉', text: 'Celebrate the season with exclusive deals up to {{discount}}% off storewide.', imageUrl: 'https://images.unsplash.com/photo-1512389142860-9c449e58a543?auto=format&fit=crop&w=1200&q=80', backgroundColor: '#fff1f2', textColor: '#9f1239', textAlign: 'center', padding: 36, radius: 0 },
      { id: 3, type: 'coupon', label: 'Code', icon: 'sell', title: 'Your exclusive code', text: '{{promo_code}}', secondaryText: '{{discount}}% off · Ends {{end_date}}', backgroundColor: '#fff1f2', textColor: '#be123c', textAlign: 'center', padding: 28, radius: 12 },
      { id: 4, type: 'button', label: 'Shop', icon: 'smart_button', text: 'Shop the Sale →', url: '{{shop_url}}', backgroundColor: '#ffffff', buttonColor: '#dc2626', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'delivery-failed',
    name: 'Delivery Failed',
    description: 'Failed delivery notification with redelivery scheduling and support contact.',
    icon: 'package_2',
    category: 'Logistics',
    accentColor: '#ea580c',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Delivery Status', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'badge', label: 'Status', icon: 'verified', text: '⚠️ Delivery Attempt Failed', backgroundColor: '#fff7ed', textColor: '#9a3412', textAlign: 'center', padding: 20, radius: 999 },
      { id: 3, type: 'text', label: 'Info', icon: 'subject', title: "We couldn't deliver your package", text: 'Our courier attempted delivery for order #{{order_id}} but was unable to complete it. Please reschedule or pick up from the depot.', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 28, radius: 0 },
      { id: 4, type: 'button', label: 'Reschedule', icon: 'smart_button', text: 'Reschedule Delivery', url: '{{reschedule_url}}', backgroundColor: '#ffffff', buttonColor: '#ea580c', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} Logistics · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'game-achievement',
    name: 'Game Achievement',
    description: 'Gaming milestone email celebrating a user achievement with reward details.',
    icon: 'emoji_events',
    category: 'Gaming',
    accentColor: '#d97706',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{game_name}}', text: 'Achievements', url: 'https://nowmail.app', backgroundColor: '#1c1917', textColor: '#fef3c7', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'hero', label: 'Achievement', icon: 'image', title: '🏆 Achievement Unlocked!', text: 'You earned the "{{achievement_name}}" badge. Keep it up, {{first_name}}!', imageUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80', backgroundColor: '#1c1917', textColor: '#fef3c7', textAlign: 'center', padding: 36, radius: 0 },
      { id: 3, type: 'coupon', label: 'Reward', icon: 'sell', title: 'Your reward', text: '+{{reward_points}} XP', secondaryText: 'Bonus: {{bonus_item}}', backgroundColor: '#292524', textColor: '#fbbf24', textAlign: 'center', padding: 28, radius: 12 },
      { id: 4, type: 'button', label: 'Play', icon: 'smart_button', text: 'Continue Playing →', url: '{{game_url}}', backgroundColor: '#1c1917', buttonColor: '#d97706', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{game_name}} · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#1c1917', textColor: '#78716c', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'bank-transaction',
    name: 'Bank Transaction Alert',
    description: 'Real-time banking transaction notification with amount, merchant, and fraud alert link.',
    icon: 'account_balance',
    category: 'Banking',
    accentColor: '#1d4ed8',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{bank_name}}', text: 'Transaction Alert', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'badge', label: 'Alert', icon: 'verified', text: '💳 Transaction Processed', backgroundColor: '#eff6ff', textColor: '#1e3a8a', textAlign: 'center', padding: 20, radius: 999 },
      { id: 3, type: 'list', label: 'Transaction', icon: 'format_list_bulleted', title: 'Transaction Details', text: 'Amount: {{amount}}\nMerchant: {{merchant}}\nDate: {{transaction_date}}\nAccount: {{account_last4}}\nBalance: {{balance}}', backgroundColor: '#eff6ff', textColor: '#1e3a8a', textAlign: 'left', padding: 28, radius: 0 },
      { id: 4, type: 'button', label: 'Report', icon: 'smart_button', text: 'Not you? Report Fraud', url: '{{fraud_url}}', backgroundColor: '#ffffff', buttonColor: '#dc2626', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{bank_name}} · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'loyalty-points',
    name: 'Loyalty Points Earned',
    description: 'Retail loyalty program update showing points earned, balance, and redemption CTA.',
    icon: 'loyalty',
    category: 'Retail',
    accentColor: '#9333ea',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}} Rewards', text: 'My Points', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'text', label: 'Update', icon: 'subject', title: "You've earned {{points_earned}} points! ⭐", text: 'Your recent purchase has been credited to your rewards account. Here is your updated balance.', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 32, radius: 0 },
      { id: 3, type: 'coupon', label: 'Balance', icon: 'sell', title: 'Total Points Balance', text: '{{total_points}} pts', secondaryText: 'Redeem for {{redemption_value}} in rewards', backgroundColor: '#faf5ff', textColor: '#7e22ce', textAlign: 'center', padding: 28, radius: 12 },
      { id: 4, type: 'button', label: 'Redeem', icon: 'smart_button', text: 'Redeem Points →', url: '{{redeem_url}}', backgroundColor: '#ffffff', buttonColor: '#9333ea', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} Rewards · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'server-deployment',
    name: 'Deployment Notification',
    description: 'IT/DevOps deployment success or failure notification with release notes link.',
    icon: 'deployed_code',
    category: 'IT / DevOps',
    accentColor: '#0284c7',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}} DevOps', text: 'Deployment Alert', url: 'https://nowmail.app', backgroundColor: '#0f172a', textColor: '#f1f5f9', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'badge', label: 'Status', icon: 'verified', text: '✅ Deployment Successful', backgroundColor: '#ecfdf5', textColor: '#065f46', textAlign: 'center', padding: 18, radius: 999 },
      { id: 3, type: 'list', label: 'Deploy Info', icon: 'format_list_bulleted', title: 'Deployment Details', text: 'Service: {{service_name}}\nVersion: {{version}}\nEnvironment: {{environment}}\nDeployed by: {{deployed_by}}\nTime: {{deploy_time}}', backgroundColor: '#0f172a', textColor: '#94a3b8', textAlign: 'left', padding: 28, radius: 0 },
      { id: 4, type: 'button', label: 'Release Notes', icon: 'smart_button', text: 'View Release Notes', url: '{{release_url}}', backgroundColor: '#0f172a', buttonColor: '#0284c7', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} Engineering · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#0f172a', textColor: '#475569', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'webinar-invite',
    name: 'Webinar Invitation',
    description: 'Live webinar invite with speaker bio, agenda preview, and registration CTA.',
    icon: 'videocam',
    category: 'Events',
    accentColor: '#0ea5e9',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Webinars', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'hero', label: 'Hero', icon: 'image', title: "📡 Join Us Live: {{webinar_title}}", text: 'A free live session with {{speaker_name}} on {{webinar_date}} at {{webinar_time}}.', imageUrl: 'https://images.unsplash.com/photo-1591115765373-5207764f72e7?auto=format&fit=crop&w=1200&q=80', backgroundColor: '#f0f9ff', textColor: '#0c4a6e', textAlign: 'center', padding: 36, radius: 0 },
      { id: 3, type: 'list', label: 'Agenda', icon: 'format_list_bulleted', title: "What you'll learn", text: '{{topic_1}}\n{{topic_2}}\n{{topic_3}}\nLive Q&A with {{speaker_name}}', backgroundColor: '#f0f9ff', textColor: '#0c4a6e', textAlign: 'left', padding: 28, radius: 0 },
      { id: 4, type: 'button', label: 'Register', icon: 'smart_button', text: 'Register for Free →', url: '{{register_url}}', backgroundColor: '#ffffff', buttonColor: '#0ea5e9', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'support-ticket-opened',
    name: 'Support Ticket Opened',
    description: 'Customer support ticket confirmation with ticket number and expected response time.',
    icon: 'support_agent',
    category: 'Support',
    accentColor: '#0891b2',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}} Support', text: 'Help Center', url: 'https://nowmail.app/support', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'badge', label: 'Status', icon: 'verified', text: '🎟 Ticket #{{ticket_id}} Received', backgroundColor: '#e0f2fe', textColor: '#0c4a6e', textAlign: 'center', padding: 18, radius: 999 },
      { id: 3, type: 'text', label: 'Confirm', icon: 'subject', title: "We've received your request", text: 'Our support team will review your ticket and get back to you within {{response_time}}. You can track your ticket status anytime.', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 28, radius: 0 },
      { id: 4, type: 'button', label: 'View Ticket', icon: 'smart_button', text: 'View Ticket Status', url: '{{ticket_url}}', backgroundColor: '#ffffff', buttonColor: '#0891b2', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} Support · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'product-restock',
    name: 'Back in Stock',
    description: 'Restock alert for wishlisted items with product details and quick buy CTA.',
    icon: 'inventory',
    category: 'E-Commerce',
    accentColor: '#16a34a',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Shop Now', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'badge', label: 'Alert', icon: 'verified', text: '🎉 Back in Stock!', backgroundColor: '#f0fdf4', textColor: '#14532d', textAlign: 'center', padding: 20, radius: 999 },
      { id: 3, type: 'text', label: 'Info', icon: 'subject', title: "Good news, {{first_name}}! {{product_name}} is back!", text: 'The item on your wishlist is available again. Grab it before it sells out — these go fast!', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 28, radius: 0 },
      { id: 4, type: 'button', label: 'Buy Now', icon: 'smart_button', text: 'Shop Now →', url: '{{product_url}}', backgroundColor: '#ffffff', buttonColor: '#16a34a', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'certificate-issued',
    name: 'Certificate Issued',
    description: 'Course completion certificate email with achievement summary and download CTA.',
    icon: 'workspace_premium',
    category: 'Education',
    accentColor: '#b45309',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Certificates', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'hero', label: 'Hero', icon: 'image', title: '🎓 Congratulations, {{first_name}}!', text: "You've successfully completed {{course_name}}. Your certificate is ready.", imageUrl: 'https://images.unsplash.com/photo-1523289333742-be1143f6b766?auto=format&fit=crop&w=1200&q=80', backgroundColor: '#fffbeb', textColor: '#78350f', textAlign: 'center', padding: 36, radius: 0 },
      { id: 3, type: 'list', label: 'Details', icon: 'format_list_bulleted', title: 'Certificate Details', text: 'Course: {{course_name}}\nCompleted: {{completion_date}}\nCertificate ID: {{cert_id}}\nIssued by: {{company_name}}', backgroundColor: '#fffbeb', textColor: '#78350f', textAlign: 'left', padding: 28, radius: 0 },
      { id: 4, type: 'button', label: 'Download', icon: 'smart_button', text: 'Download Certificate', url: '{{cert_url}}', backgroundColor: '#ffffff', buttonColor: '#b45309', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} Education · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'policy-update',
    name: 'Policy Update',
    description: 'Terms of service or privacy policy update notification with change summary.',
    icon: 'gavel',
    category: 'Compliance',
    accentColor: '#475569',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Policy Update', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'text', label: 'Notice', icon: 'subject', title: 'Important update to our {{policy_name}}', text: "We're updating our {{policy_name}} effective {{effective_date}}. Here's a summary of the key changes.", backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 32, radius: 0 },
      { id: 3, type: 'list', label: 'Changes', icon: 'format_list_bulleted', title: 'Key Changes', text: '{{change_1}}\n{{change_2}}\n{{change_3}}', backgroundColor: '#f8fafc', textColor: '#475569', textAlign: 'left', padding: 28, radius: 0 },
      { id: 4, type: 'button', label: 'Review', icon: 'smart_button', text: 'Review Full Policy', url: '{{policy_url}}', backgroundColor: '#ffffff', buttonColor: '#475569', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} Legal · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'insurance-renewal',
    name: 'Insurance Renewal',
    description: 'Insurance policy renewal reminder with coverage summary and premium details.',
    icon: 'health_and_safety',
    category: 'Insurance',
    accentColor: '#0369a1',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Policy Renewal', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'text', label: 'Notice', icon: 'subject', title: 'Your policy renews on {{renewal_date}}', text: 'Your {{policy_type}} policy #{{policy_number}} is due for renewal. Review your coverage and renew to stay protected.', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 32, radius: 0 },
      { id: 3, type: 'list', label: 'Policy Info', icon: 'format_list_bulleted', title: 'Policy Details', text: 'Policy: {{policy_number}}\nType: {{policy_type}}\nRenewal Date: {{renewal_date}}\nPremium: {{premium_amount}}', backgroundColor: '#e0f2fe', textColor: '#0c4a6e', textAlign: 'left', padding: 28, radius: 0 },
      { id: 4, type: 'button', label: 'Renew', icon: 'smart_button', text: 'Renew My Policy', url: '{{renew_url}}', backgroundColor: '#ffffff', buttonColor: '#0369a1', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} Insurance · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'content-digest',
    name: 'Content Digest',
    description: 'Media weekly content digest with top articles, podcast episodes, and video links.',
    icon: 'rss_feed',
    category: 'Media',
    accentColor: '#e11d48',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}} Digest', text: 'View online', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'text', label: 'Intro', icon: 'subject', title: "This week's best content 🎬", text: "Here's your weekly roundup of the top articles, videos, and podcasts curated just for you.", backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 28, radius: 0 },
      { id: 3, type: 'list', label: 'Top Picks', icon: 'format_list_bulleted', title: 'Top Picks This Week', text: '📰 {{article_1}}\n🎧 {{podcast_1}}\n📹 {{video_1}}\n🔥 Trending: {{trending_topic}}', backgroundColor: '#fff1f2', textColor: '#881337', textAlign: 'left', padding: 28, radius: 0 },
      { id: 4, type: 'button', label: 'Explore', icon: 'smart_button', text: 'Explore All Content →', url: '{{content_url}}', backgroundColor: '#ffffff', buttonColor: '#e11d48', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} Media · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'vehicle-service',
    name: 'Vehicle Service Reminder',
    description: 'Automotive service due reminder with mileage details and booking CTA.',
    icon: 'directions_car',
    category: 'Automotive',
    accentColor: '#374151',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{dealership_name}}', text: 'Service Center', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'text', label: 'Info', icon: 'subject', title: 'Time for your {{service_type}}', text: 'Your {{vehicle_year}} {{vehicle_make}} {{vehicle_model}} is due for its {{service_type}}. Keep your vehicle in top condition.', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 28, radius: 0 },
      { id: 3, type: 'list', label: 'Details', icon: 'format_list_bulleted', title: 'Service Info', text: 'Vehicle: {{vehicle_year}} {{vehicle_make}} {{vehicle_model}}\nService: {{service_type}}\nDue at: {{due_mileage}} miles', backgroundColor: '#f1f5f9', textColor: '#1e293b', textAlign: 'left', padding: 28, radius: 0 },
      { id: 4, type: 'button', label: 'Book', icon: 'smart_button', text: 'Book a Service Appointment', url: '{{booking_url}}', backgroundColor: '#ffffff', buttonColor: '#374151', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{dealership_name}} · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'restaurant-reservation',
    name: 'Restaurant Reservation',
    description: 'Dining reservation confirmation with table details, location, and menu preview.',
    icon: 'restaurant',
    category: 'Hospitality',
    accentColor: '#b91c1c',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{restaurant_name}}', text: 'Reservations', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'badge', label: 'Status', icon: 'verified', text: '🍽 Reservation Confirmed!', backgroundColor: '#fef2f2', textColor: '#991b1b', textAlign: 'center', padding: 20, radius: 999 },
      { id: 3, type: 'list', label: 'Booking', icon: 'format_list_bulleted', title: 'Your Booking', text: 'Date: {{reservation_date}}\nTime: {{reservation_time}}\nGuests: {{guest_count}}\nRef: {{reservation_ref}}', backgroundColor: '#fef2f2', textColor: '#991b1b', textAlign: 'left', padding: 28, radius: 0 },
      { id: 4, type: 'button', label: 'Manage', icon: 'smart_button', text: 'Manage Reservation', url: '{{reservation_url}}', backgroundColor: '#ffffff', buttonColor: '#b91c1c', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{restaurant_name}} · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'crypto-alert',
    name: 'Crypto Price Alert',
    description: 'Cryptocurrency price alert notification with market data and trade CTA.',
    icon: 'currency_bitcoin',
    category: 'Crypto / Finance',
    accentColor: '#f59e0b',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Price Alerts', url: 'https://nowmail.app', backgroundColor: '#0f172a', textColor: '#fef3c7', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'text', label: 'Alert', icon: 'subject', title: '{{coin_name}} hit {{alert_price}}!', text: '{{coin_name}} ({{coin_symbol}}) has reached your target price. Current price: {{current_price}}.', backgroundColor: '#0f172a', textColor: '#e2e8f0', textAlign: 'center', padding: 28, radius: 0 },
      { id: 3, type: 'list', label: 'Market Data', icon: 'format_list_bulleted', title: 'Market Snapshot', text: 'Price: {{current_price}}\n24h Change: {{change_24h}}\nMarket Cap: {{market_cap}}', backgroundColor: '#1e293b', textColor: '#94a3b8', textAlign: 'left', padding: 28, radius: 0 },
      { id: 4, type: 'button', label: 'Trade', icon: 'smart_button', text: 'Trade Now →', url: '{{trade_url}}', backgroundColor: '#0f172a', buttonColor: '#f59e0b', buttonTextColor: '#000000', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} · Crypto investments carry risk. Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#0f172a', textColor: '#475569', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'account-verified',
    name: 'Account Verified',
    description: 'Email verification success confirmation with next steps and profile setup guide.',
    icon: 'verified',
    category: 'Authentication',
    accentColor: '#10b981',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Account Setup', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'badge', label: 'Status', icon: 'verified', text: '✅ Email Verified Successfully!', backgroundColor: '#ecfdf5', textColor: '#065f46', textAlign: 'center', padding: 20, radius: 999 },
      { id: 3, type: 'list', label: 'Next Steps', icon: 'format_list_bulleted', title: 'Complete your setup', text: 'Complete your profile\nSet your preferences\nExplore key features\nInvite your team', backgroundColor: '#ecfdf5', textColor: '#065f46', textAlign: 'left', padding: 28, radius: 0 },
      { id: 4, type: 'button', label: 'Get Started', icon: 'smart_button', text: 'Get Started →', url: '{{dashboard_url}}', backgroundColor: '#ffffff', buttonColor: '#10b981', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'survey-invite',
    name: 'Survey Invitation',
    description: 'Customer satisfaction survey with estimated time and incentive for completion.',
    icon: 'poll',
    category: 'Marketing',
    accentColor: '#6366f1',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Your Opinion Matters', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'text', label: 'Ask', icon: 'subject', title: 'Share your thoughts, {{first_name}}!', text: "We'd love to hear about your experience. Your feedback shapes our product roadmap.", backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 32, radius: 0 },
      { id: 3, type: 'coupon', label: 'Reward', icon: 'sell', title: 'Complete the survey to win', text: '{{prize_value}} Gift Card', secondaryText: 'Takes only {{survey_time}} minutes', backgroundColor: '#eef2ff', textColor: '#3730a3', textAlign: 'center', padding: 28, radius: 12 },
      { id: 4, type: 'button', label: 'Take Survey', icon: 'smart_button', text: 'Take the Survey →', url: '{{survey_url}}', backgroundColor: '#ffffff', buttonColor: '#6366f1', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'project-update',
    name: 'Project Status Update',
    description: 'Project management stakeholder update with milestones, blockers, and next steps.',
    icon: 'task_alt',
    category: 'Corporate',
    accentColor: '#0891b2',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Project Updates', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'text', label: 'Status', icon: 'subject', title: '{{project_name}} — Status Update', text: 'Latest update for {{project_name}} as of {{update_date}}. Overall status: {{project_status}}.', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'left', padding: 28, radius: 0 },
      { id: 3, type: 'list', label: 'Progress', icon: 'format_list_bulleted', title: 'Progress Summary', text: 'Completed: {{completed_tasks}}\nIn Progress: {{in_progress_tasks}}\nBlockers: {{blockers}}\nNext Milestone: {{next_milestone}}', backgroundColor: '#e0f2fe', textColor: '#0c4a6e', textAlign: 'left', padding: 28, radius: 0 },
      { id: 4, type: 'button', label: 'Dashboard', icon: 'smart_button', text: 'View Project Dashboard', url: '{{project_url}}', backgroundColor: '#ffffff', buttonColor: '#0891b2', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'subscription-cancelled',
    name: 'Subscription Cancelled',
    description: 'Cancellation confirmation with access end date, win-back offer, and resubscribe CTA.',
    icon: 'cancel',
    category: 'SaaS',
    accentColor: '#64748b',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'Account', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'text', label: 'Confirm', icon: 'subject', title: "We're sorry to see you go, {{first_name}}", text: 'Your {{plan_name}} subscription has been cancelled. You will continue to have access until {{access_end_date}}.', backgroundColor: '#ffffff', textColor: '#374151', textAlign: 'center', padding: 32, radius: 0 },
      { id: 3, type: 'coupon', label: 'Win-back', icon: 'sell', title: 'Come back with a special offer', text: 'COMEBACK30', secondaryText: '30% off if you resubscribe within 30 days', backgroundColor: '#f8fafc', textColor: '#475569', textAlign: 'center', padding: 28, radius: 12 },
      { id: 4, type: 'button', label: 'Resubscribe', icon: 'smart_button', text: 'Reactivate My Account', url: '{{reactivate_url}}', backgroundColor: '#ffffff', buttonColor: '#64748b', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
  {
    id: 'partner-announcement',
    name: 'Partnership Announcement',
    description: 'Business partnership announcement with collaboration benefits and joint CTA.',
    icon: 'handshake',
    category: 'Corporate',
    accentColor: '#7c3aed',
    blocks: [
      { id: 1, type: 'header', label: 'Header', icon: 'view_headline', title: '{{company_name}}', text: 'News', url: 'https://nowmail.app', backgroundColor: '#ffffff', textColor: '#0f172a', textAlign: 'left', padding: 22, radius: 0 },
      { id: 2, type: 'hero', label: 'Hero', icon: 'image', title: '🤝 {{company_name}} × {{partner_name}}', text: "We're thrilled to announce our new partnership with {{partner_name}} to bring you even more value.", imageUrl: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80', backgroundColor: '#faf5ff', textColor: '#4c1d95', textAlign: 'center', padding: 36, radius: 0 },
      { id: 3, type: 'list', label: 'Benefits', icon: 'format_list_bulleted', title: 'What this means for you', text: '{{benefit_1}}\n{{benefit_2}}\n{{benefit_3}}', backgroundColor: '#faf5ff', textColor: '#4c1d95', textAlign: 'left', padding: 28, radius: 0 },
      { id: 4, type: 'button', label: 'Learn More', icon: 'smart_button', text: 'Learn More →', url: '{{partnership_url}}', backgroundColor: '#ffffff', buttonColor: '#7c3aed', buttonTextColor: '#ffffff', textAlign: 'center', padding: 24, radius: 8 },
      { id: 5, type: 'footer', label: 'Footer', icon: 'notes', text: '{{company_name}} · Unsubscribe: {{unsubscribe_url}}', backgroundColor: '#f8fafc', textColor: '#94a3b8', textAlign: 'center', padding: 24, radius: 0 },
    ],
  },
];
