name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Root Dependencies
        run: npm install

      - name: Build Library
        run: npm run build

      - name: Pack Library
        run: |
          cd dist
          npm pack
          echo "TARBALL=$(ls *.tgz)" >> $GITHUB_ENV

      - name: Build UI App
        run: |
          cd template-builder
          npm install ../dist/${{ env.TARBALL }} --force
          npm install
          npm run build -- --base-href /nowmail-email-teamplate-builder/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: template-builder/dist/template-builder/browser
          branch: gh-pages
