name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Library
        run: npm run build

      - name: Pack Library
        run: |
          cd dist
          npm pack
          echo "TARBALL=$(ls *.tgz)" >> $GITHUB_ENV

      - name: Install Library in Demo App
        run: |
          cd template-builder
          npm install ../dist/${{ env.TARBALL }} --force
          npm install

      - name: Build Demo App
        run: |
          cd template-builder
          npm run build -- --configuration production --base-href /nowmail-email-teamplate-builder/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: template-builder/dist/template-builder/browser